### ISSUE TITLE
Login not persisting

### ISSUE THREAD

**Issue by ageis** [keybase/pykeybasebot#40]
Hello,

I am probably doing something unusual here with asyncio; basically my concept called for running aiohttp and pykeybasebot at the same time (I want my bot to listen to the channel and also receive webhooks) and I wasn't sure how else to do that (have tried threading, etc.) so I just throw two asyncio future tasks into the event loop.

My code is here: [https://gist.github.com/ageis/b29b2565aecabe6e96e63460e26155fe](https://gist.github.com/ageis/b29b2565aecabe6e96e63460e26155fe) it's a simple server listening on port 8080 plus sitting in a Keybase channel via your library. I've omitted the message handler, it's immaterial to the bug.

What I'm finding is that my bot successfully receives several webhooks and posts them to the channel, but then its authentication fails or something. This is being run on a headless server. So I have the systemd service running in my user session, I did `keybase login` before running the script, and I also export `KEYBASE_PAPERKEY` to the environment. In addition, the script has the correct paperkey hardcoded in the bot instantiation. 

Any ideas why this would work initially and then throw "Login required" ?

```2020-01-17 05:17:22.608 ERROR {web_protocol} [log_exception] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "keybase_alerts.py", line 82, in handle
    await alert_bot.chat.send(channel, msg)
  File "/usr/local/lib/python3.7/dist-packages/pykeybasebot/chat_client.py", line 18, in send
    "message": {"body": message},
  File "/usr/local/lib/python3.7/dist-packages/pykeybasebot/chat_client.py", line 98, in execute
    resp = await self.bot.submit("chat api", json.dumps(command).encode("utf-8"))
  File "/usr/local/lib/python3.7/dist-packages/pykeybasebot/bot.py", line 95, in submit
    self.keybase_cli, command, input_data, loop=self.loop, **opts
  File "/usr/local/lib/python3.7/dist-packages/pykeybasebot/cli.py", line 78, in kbsubmit
    raise Exception(parsed_response["error"])
Exception: {'code': 0, 'message': 'Login required'}
````

Judging from the traceback, I suppose it's possible that "Login required" is my aiohttp server's reply to the client (in this case Alertmanager with a POST request), except I didn't specify basic auth anywhere so I've no clue why that would pop up. It's my first time using aiohttp incidentally. Let me know if that makes more sense; if the other library is to blame... I don't think it is though since after the first few webhooks, they continue to flow in yet aren't sent onward to the Keybase channel.

**Comment by ageis** [comment]
cc @xgess

**Comment by xgess** [comment]
hey - thanks for the ping. i (or someone) will take a look. do you mind, if possible doing a `keybase log send` from the keybase instance after the bot throws this error? it could definitely help to see what's happening in the keybase service when this happens.

**Comment by xgess** [comment]
ok. poked around a little bit, and i can't dupe what you're seeing. BUT i can share a couple things that might help. first is that the bot has a teardown function that gets called when it's shutting down if it thinks it did the login process (whether or not you passed in a paperkey). so you could try either not doing the login yourself ahead of time, or not passing in the paperkey. probably the latter. this will prevent the bot from ever logging out. it looks like what you're seeing is a logged out running keybase service. so maybe a sporadic error from the keybase service which is otherwise recoverable is bubbling up and triggering the logout in a way that you're not set up to recover from. my guess from other keybase bots, is that this is an async timeout. 

so here are my suggestions:
1. if you're going to do the login of the keybase user yourself before spinning anything up, stop passing in the paperkey to the bot on initialization
2. i have a bot that is posting large chat messages from a resource-limited docker container, and it sometimes gets async timeout errors. i worked around it by wrapping the calls to sending chat messages in something that can retry them for that error. not exactly the prettiest solution, but it works well. if you are seeing async timeouts from chat sends, please let me know. maybe we can look into pushing this logic down into the framework. https://github.com/xgess/keybase_merkle_prover/blob/master/code/task.py#L63

**Comment by ageis** [comment]
Hey @xgess thanks for the suggestions. Incidentally I was averse to providing a log, but #1 worked for me.

Tried starting from an initial logged-out state with the Keybase systemd user session, and instantiated the bot with a paperkey. The problem persisted.

Then as you suggested I had Keybase logged in before starting the script, however I removed "paperkey" from the pykeybasebot.Bot arguments (I hadn't known this was possible before). Under these circumstances the bot is now functioning for my intended purposes, the session is persisted without errors.

I appreciate you sharing your async code, I'll check it out. I haven't run up against timeouts yet; I've actually been fairly impressed with the throughput and zero messages dropped. So far my bot has handled more than a few unintended Alertmanager floods.

Saw the new version and bots announcement earlier, I'll be sure to keep up with developments.

I think you can close this ticket... But I highly recommend providing something in "examples" which shows how one could simultaneously listen for webhooks or have a HTTP REST API capability in addition to listening to events in a Keybase channel. Thanks!

**Comment by ageis** [comment]
Ephemeral comment -- and if Keybase ever needs a sysadmin/devops/security engineer, I would be right there. I know ya'll have my information :)
